services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=mybatis-flex
    ports:
      - 3306:3306
    restart: always
    command:
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
    labels:
      #      org.springframework.boot.ignore: true
      org.springframework.boot.service-connection: mysql
    networks:
      - mybatis-flex
# 定义网络，可以多个，如果不声明，默认会创建一个网络名称为“工程名称_default”的bridge网络
networks:
  mybatis-flex: # 一个具体网络的条目名称
    name: mybatis-flex # 网络名称，默认为“工程名称_网络条目名称”
    driver: bridge # 网络模式，默认为 bridge
