spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-flex
    username: root
    password: 123456
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    out-of-order: true
    clean-disabled: false
    clean-on-validation-error: true
  docker:
    compose:
      enabled: true
      host: 127.0.0.1
      file: docker-compose.yaml